# Configuration file for CogniCore

# =============================
# General LLM Parameters
# =============================
# These parameters are used by default for text generation, but can be overridden.
# Supported LLM models/providers examples:
#   - llm_model: "gemini-2.5-flash-preview-04-17"   llm_provider: "google"
#   - llm_model: "llama-3-70b"                       llm_provider: "groq"
#   - llm_model: "meta-llama/llama-4-scout-17b-16e-instruct" llm_provider: "groq"
#   - llm_model: "gemma2:2b"                         llm_provider: "ollama"
llm_model: "gemini-2.5-flash" #this is the stable reallease, not the preview
llm_provider: "google"
temperature: 1.0
max_tokens: 8000
top_k: 45
top_p: 0.95
stream: false
cot_enabled: false
save_answer: false
prompt_language: "en"

# =============================
# Vision Model Parameters
# =============================
# Used by ImageAnalyzerAgent
# Supported vision models/providers examples:
#   - vision_model: "gemini-2.5-flash-preview-04-17"   vision_provider: "gemini"
#   - vision_model: "llama-3.2-90b-vision-preview"     vision_provider: "groq"
#   - vision_model: "florence-2"                       vision_provider: "huggingface"
vision_model: "gemini-2.5-flash" # this is the stable release, not the preview
vision_provider: "gemini"

# =============================
# Text Classifier Parameters
# =============================
# Used by TextClassifier
# Supported classifier models/providers examples:
#   - text_classifier_model: "meta-llama/llama-4-scout-17b-16e-instruct" text_classifier_provider: "groq"
#   - text_classifier_model: "gemini-2.5-flash-preview-04-17" text_classifier_provider: "google"
text_classifier_model: "qwen/qwen3-32b"
text_classifier_provider: "groq"
classifier_system_prompt: "You are an agent in charge of classifying user's queries into different categories of tasks."
classification_labels_dict:
  0: {class_name: "question", description: "A general question about any topic."}
  2: {class_name: "internet_search", description: "A request to search for information on the internet."}

# =============================
# Image Classifier Parameters
# =============================
# Used by ImageClassifier
# Supported image classifier models/providers examples:
#   - image_classifier_model: "gemini-1.5-flash" image_classifier_provider: "gemini"
#   - image_classifier_model: "llama-3.2-90b-vision-preview" image_classifier_provider: "groq"
image_classifier_model: "gemini-1.5-flash"
image_classifier_provider: "gemini"
image_classifier_system_prompt: "You are an agent that classifies images."
image_classification_labels_dict:
  0: {class_name: "animal", description: "Image containing an animal."}
  1: {class_name: "city", description: "Image representing a city or an urban place."}
  2: {class_name: "other", description: "Any other type of image."}

# =============================
# Internet Searcher Parameters
# =============================
# Used by InternetSearcher
# Supported searcher models/providers examples:
#   - internet_search_model: "compound-beta" internet_search_provider: "groq"
internet_search_model: "compound-beta"
internet_search_provider: "groq"

# =============================
# Other Parameters
# =============================
# Agentic RAG parameters
rag_query_breaker_model: "o1-mini"
rag_query_breaker_provider: "github"

# Entity description parameters
description_model_name: "gemma2:2b"
description_llm_provider: "ollama"

# File paths
watermark_removal_output_dir: "C:/Users/Yanis/Documents/AI Art/watermarked_removed"
captioned_videos_output_dir: "output/captioned_videos"